export const RECEIVE_ADDRESS = "receive_address";
export const RECEIVE_CATEGORYS = "receive_categorys";
export const RECEIVE_SHOPS = "receive_shops";
export const RECEIVE_USER_INFO = "reiceive_user_info";
export const RESET_USER_INFO = "reset_user_info"; // 重置用户信息
export const RECEIVE_GOODS = "receive_goods"; // 获取商家商品
export const RECEIVE_INFO = "receive_info"; // 获取商家信息
export const RECEIVE_RATINGS = "receive_ratings"; // 获取商家评价
export const INCREMENT_FOOD_COUNT = "increment_food_count"; // 增加商品数量
export const DECREMENT_FOOD_COUNT = "decrement_food_count"; // 减少商品数量
export const CLEAR_CART = "clear_cart"; // 清空购物车
export const RECEIVE_SEARCH_SHOPS = "receive_search_shops"; // 清空购物车
